name:               typescript
version:            0.1.0.0
author:             "Vest"
copyright:          "2018 Vest"

extra-source-files:
- README.md

synopsis:           TypeScript code generation for interfacing with our Haskell-based backend.
category:           Network
description:        See README.md.

dependencies:
- aeson             >= 1.4
- aeson-typescript  >= 0.1
- base              >= 4.10
- directory         >= 1.3
- ede               >= 0.2
- filepath          >= 1.4
- random            >= 1.1
- services
- text              >= 1.2
- text-replace      >= 0.0
- template-haskell  >= 2.13
- utf8-string       >= 1.0
- vest-base

# The default-extensions and ghc-options were inspired by this post (and modified for convenience):
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wpartial-fields
- -Wno-name-shadowing
- -fno-warn-orphans

library:
  source-dirs: src

executables:
  ts-callers:
    main:           Callers.hs
    other-modules:  []
    source-dirs:    bin
    dependencies:
    - typescript
  ts-types:
    main:           Types.hs
    other-modules:  []
    source-dirs:    bin
    dependencies:
    - typescript
