# HLint takes a subset of the extensions we use... Be sure to keep this in sync with .hindent.yaml
# and the various package.yaml files.
- arguments:
  - -XAllowAmbiguousTypes
  - -XApplicativeDo
  - -XBangPatterns
  - -XConstraintKinds
  - -XDataKinds
  - -XDefaultSignatures
  - -XDeriveAnyClass
  - -XDeriveDataTypeable
  - -XDeriveFoldable
  - -XDeriveFunctor
  - -XDeriveGeneric
  - -XDeriveLift
  - -XDeriveTraversable
  - -XDerivingStrategies
  - -XDuplicateRecordFields
  - -XEmptyCase
  - -XExistentialQuantification
  - -XFlexibleContexts
  - -XFlexibleInstances
  - -XFunctionalDependencies
  - -XGADTs
  - -XGeneralizedNewtypeDeriving
  - -XInstanceSigs
  - -XKindSignatures
  - -XLambdaCase
  - -XMultiParamTypeClasses
  - -XMultiWayIf
  - -XNamedFieldPuns
  - -XNoImplicitPrelude
  - -XOverloadedStrings
  - -XOverloadedLabels
  - -XPatternSynonyms
  - -XPolyKinds
  - -XQuasiQuotes
  - -XRankNTypes
  - -XScopedTypeVariables
  - -XStandaloneDeriving
  - -XTemplateHaskell
  - -XTupleSections
  - -XTypeApplications
  - -XTypeFamilies
  - -XTypeFamilyDependencies
  - -XTypeOperators
  - -XUndecidableInstances

- fixity: infixl 1 >>-
- fixity: infixr 8 :<|>
