resolver: lts-12.10

packages:
- bridge
- bridge-client
# - core
- price-server
- vest-prelude

extra-deps:
- aeson-1.4.1.0
- beam-postgres-0.3.2.2
- safe-money-0.7
- safe-money-aeson-0.1
- streamly-0.5.1
- stripe-core-2.4.0
- stripe-haskell-2.4.0
- stripe-http-client-2.4.0
- timers-updatable-0.2.0.2

flags:
  o-clock:
    aeson: true
    hashable: true