resolver: lts-12.10

packages:
- bridge
# - bridge-client
# - core
# - fiat-payment-server
# - manager
# - price-server
- vest-prelude

extra-deps:
- aeson-1.4.1.0
- beam-postgres-0.3.2.2
- safe-money-0.7
- safe-money-aeson-0.1
- streamly-0.5.1
- text-replace-0.0.0.3

flags:
  o-clock:
    aeson: true
    hashable: true