resolver: lts-12.10

packages:
- typescript
- services
- tezos
- vest-base

extra-deps:
- aeson-1.4.1.0
- beam-postgres-0.3.2.2
- ede-0.2.9
- safe-money-0.7
- safe-money-aeson-0.1
- streamly-0.5.1
- text-format-0.3.2
- text-replace-0.0.0.3
- yaml-0.10.2.0
# Remove this when hindent > 5.2.7 is published to hackage (for configurable extensions).
- github: commercialhaskell/hindent
  commit: ffe03701050d159387c06103ecaf8147716d5cb8

flags:
  o-clock:
    aeson: true
    hashable: true
