name:               tezos
version:            0.1.0.0
author:             "Vest"
copyright:          "2018 Vest"

extra-source-files:
- README.md

synopsis:           TypeScript types for interfacing with our Haskell-based backend.
category:           Network
description:        See README.md.

dependencies:
- aeson             >= 1.4
- base              >= 4.10
- bytestring        >= 0.10
- casing            >= 0.1
- streamly          >= 0.5
- vest-base

# The default-extensions and ghc-options were inspired by this post (and modified for convenience):
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wpartial-fields
- -Wno-name-shadowing
- -fno-warn-orphans

library:
  source-dirs: src

executables:
  tezos-example:
    main:           Example.hs
    other-modules:  []
    source-dirs:    bin
    dependencies:
    - tezos

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tezos
