name:                vest-base
version:             0.1.0.0
author:              "Vest"
copyright:           "2018 Vest"

extra-source-files:
- README.md

synopsis:            Vest standard library.
category:            Prelude
description:         See README.md.

dependencies:
- aeson                 >= 1.3  && < 2
- amqp                  >= 0.18 && < 1
- async                 >= 2.2  && < 3
- base                  >= 4.10 && < 5
- beam-core             >= 0.7  && < 1
- beam-postgres         >= 0.3  && < 1
- containers            >= 0.5  && < 1
- cmdargs               >= 0.10 && < 1
- cryptonite            >= 0.25 && < 1
- hashable              >= 1.2  && < 2
- hashtables            >= 1.2  && < 2
- hostname              >= 1.0  && < 2
- hspec                 >= 2.5  && < 3
- http-types            >= 0.12 && < 1
- o-clock               >= 1.0  && < 2
- postgresql-simple     >= 0.5  && < 1
- protolude             >= 0.2  && < 1
- resource-pool         >= 0.2  && < 1
- safe-exceptions       >= 0.1  && < 1
- safe-money            >= 0.7  && < 1
- safe-money-aeson      >= 0.1  && < 1
- singletons            >= 2.4  && < 3
- stm                   >= 2.4  && < 3
- stm-delay             >= 0.1  && < 1
- streamly              >= 0.5  && < 1
- tagged                >= 0.8  && < 1
- text                  >= 1.2  && < 2
- time                  >= 1.8  && < 2 # Only for sql formatting time.
- unordered-containers  >= 0.2  && < 1
- utf8-string           >= 1.0  && < 2
- uuid                  >= 1.3  && < 2
- vector                >= 0.12 && < 1
- wai                   >= 3.2  && < 4
- wai-websockets        >= 3.0  && < 4
- warp                  >= 3.2  && < 4
- websockets            >= 0.12 && < 1

# The default-extensions and ghc-options have been taken from here:
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
# - GeneralizedNewtypeDeriving
- ImpredicativeTypes
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- OverloadedLabels
- PatternSynonyms
- PolyKinds # Added.
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UndecidableInstances # Added. In theory could make compiler never terminate.

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -fno-warn-orphans
# - -Wmissing-import-lists

library:
  source-dirs: src

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vest-base
