name:                vest-base
version:             0.1.0.0
author:              "Vest"
copyright:           "2018 Vest"

extra-source-files:
- README.md

synopsis:            Vest standard library.
category:            Prelude
description:         See README.md.

dependencies:
- aeson                   >= 1.3
- aeson-typescript        >= 0.1
- amqp                    >= 0.18
- async                   >= 2.2
- base                    >= 4.10
- base64-bytestring       >= 1
- beam-core               >= 0.7
- beam-postgres           >= 0.3
- blake2                  >= 0.2
- bytestring              >= 0.10
- concurrent-extra        >= 0.7
- containers              >= 0.5
- contravariant           >= 1.5
- cmdargs                 >= 0.10
- deferred-folds          >= 0.9
- ed25519                 >= 0.0
- hashable                >= 1.2
- hashtables              >= 1.2
- hedis                   >= 0.10
- hostname                >= 1.0
- http-client             >= 0.5
- http-client-tls         >= 0.3
- http-types              >= 0.12
- o-clock                 >= 1.0
- monad-parallel          >= 0.7
- mtl                     >= 2.2
- network                 >= 2.6
- pipes-concurrency       >= 2.0
- postgresql-simple       >= 0.5
- protolude               >= 0.2
- random                  >= 1.1
- resource-pool           >= 0.2
- safe-exceptions         >= 0.1
- safe-money              >= 0.7
- safe-money-aeson        >= 0.1
- servant                 >= 0.14
- servant-client          >= 0.14
- singletons              >= 2.4
- stm                     >= 2.4
- stm-chans               >= 3.0
- stm-containers          >= 1.1
- stm-delay               >= 0.1
- string-conversions      >= 0.4
- tagged                  >= 0.8
- tasty                   >= 1.1
- tasty-expected-failure  >= 0.11
- tasty-golden            >= 2.3
- text                    >= 1.2
- time                    >= 1.8  # Only for SQL formatting time.
- transformers            >= 0.5
- unix                    >= 2.7
- unordered-containers    >= 0.2
- utf8-string             >= 1.0
- uuid                    >= 1.3
- vector                  >= 0.12
- wai                     >= 3.2
- wai-websockets          >= 3.0
- warp                    >= 3.2
- websockets              >= 0.12

# The default-extensions and ghc-options were inspired by this post (and modified for convenience):
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImpredicativeTypes
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- OverloadedLabels
- PatternSynonyms
- PolyKinds
- QuasiQuotes
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wpartial-fields
- -Wno-name-shadowing
- -fno-warn-orphans

library:
  source-dirs: src

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fprint-potential-instances
    dependencies:
    - vest-base
