name:                vest-prelude
version:             0.1.0.0
author:              "Vest"
copyright:           "2018 Vest"

extra-source-files:
- README.md

synopsis:            Vest custom prelude (uses Protolude for standard prelude stuff).
category:            Prelude
description:         See README.md.

dependencies:
- aeson                 >= 1.4  && < 2
- async                 >= 2.2  && < 3
- base                  >= 4.10 && < 5
- hashable              >= 1.2  && < 2
- o-clock               >= 1.0  && < 2
- protolude             >= 0.2  && < 1
- safe-exceptions       >= 0.1  && < 1
- safe-money            >= 0.7  && < 1
- safe-money-aeson      >= 0.1  && < 1
- singletons            >= 2.4  && < 3
- squeal-postgresql     >= 0.4  && < 1
- stm                   >= 2.4  && < 3
- streamly              >= 0.5  && < 1
- text                  >= 1.2  && < 2
- time                  >= 1.8  && < 2 # only for sql formatting time
- timers-updatable      >= 0.2  && < 1
- utf8-string           >= 1.0  && < 2
- uuid                  >= 1.3  && < 2
- vector                >= 0.12 && < 1

# The default-extensions and ghc-options have been taken from here:
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
# - GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- OverloadedLabels
- PatternSynonyms
- PolyKinds # Added.
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UndecidableInstances # Added. In theory could make compiler never terminate.

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
# - -Wmissing-import-lists

library:
  source-dirs: src
