name:               services
version:            0.1.0.0
author:             "Vest"
copyright:          "2018 Vest"

extra-source-files:
- access-control/bin/subjects.yaml

synopsis:           Package containing all of the Vest backend services.
description:        See README.md.

dependencies:
- aeson                 >= 1.4
- aeson-typescript      >= 0.1
- base                  >= 4.10
- streamly              >= 0.5
- unordered-containers  >= 0.2
- yaml                  >= 0.10
- vest-base

# The default-extensions and ghc-options were inspired by this post (and modified for convenience):
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImpredicativeTypes
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- OverloadedLabels
- PatternSynonyms
- PolyKinds
- QuasiQuotes
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wpartial-fields
- -Wno-name-shadowing
- -fno-warn-orphans
- -fprint-potential-instances

library:
  source-dirs:
  - access-control/src
  - dummy-manager/src
  # - fiat-payment-server/src
  # - tezos-delegation-core/src
  # - tezos-dispatcher/src

executables:
  access-control:
    main:                 Main.hs
    source-dirs:          access-control/bin
    dependencies:
    - services
  dummy-manager:
    main:                 Main.hs
    source-dirs:          dummy-manager/bin
    dependencies:
    - services
  # tezos-delegation-core:
  #   main:                 Main.hs
  #   source-dirs:          tezos-delegation-core/bin
  #   dependencies:
  #   - services
  # tezos-dispatcher:
  #   main:                 Main.hs
  #   source-dirs:          tezos-dispatcher/bin
  #   dependencies:
  #   - services

tests:
  access-control-test:
    main:                       Spec.hs
    source-dirs:                access-control/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fprint-potential-instances
    dependencies:
    - services
  dummy-manager-test:
    main:                       Spec.hs
    source-dirs:                dummy-manager/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fprint-potential-instances
    dependencies:
    - services
  # tezos-delegation-core-test:
  #   main:                       Spec.hs
  #   source-dirs:                tezos-delegation-core/test
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   - -fprint-potential-instances
  #   dependencies:
  #   - services
  # tezos-dispatcher-test:
  #   main:                       Spec.hs
  #   source-dirs:                tezos-dispatcher/test
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   - -fprint-potential-instances
  #   dependencies:
  #   - services
