name:                price-server
version:             0.1.0.0
author:              "Vest"
copyright:           "2018 Vest"

extra-source-files:
- README.md

synopsis:            Pricing server for Vest derivatives.
description:         See README.md.

dependencies:
- base               >= 4.10 && < 5
- safe-money         >= 0.7  && < 1
- stm                >= 2.4  && < 3
- streamly           >= 0.5  && < 1
- bridge
- vest-prelude

# The default-extensions and ghc-options have been taken from here:
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
# - GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UndecidableInstances

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
# - -Wmissing-import-lists

library:
  source-dirs: src

executable:
  main:                Main.hs
  source-dirs:         bin
  dependencies:
  - price-server

tests:
  price-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - price-server
