name:                socket-server
version:             0.1.0.0
author:              "Vest"
copyright:           "2018 Vest"

extra-source-files:
- README.md

synopsis:            High-level library for streaming and RPCs over WebSockets.
category:            Network
description:         See README.md.

dependencies:
- aeson             >= 1.4  && < 2
- async             >= 2.2  && < 3
- base              >= 4.7  && < 5
- containers        >= 0.5  && < 0.6
- hashtables        >= 1.2  && < 2
- hspec             >= 2.5  && < 3
- hostname          >= 1.0  && < 2
- http-types        >= 0.12 && < 1
- network           >= 2.7  && < 3
- protolude         >= 0.2  && < 1
- streamly          >= 0.5  && < 1
- text              >= 1.2  && < 2
- utf8-string       >= 1.0  && < 2
- uuid              >= 1.3  && < 2
- safe              >= 0.3  && < 1
- vest-prelude
- wai               >= 3.2  && < 4
- wai-websockets    >= 3.0  && < 4
- warp              >= 3.2  && < 4
- websockets        >= 0.12 && < 1

# The default-extensions and ghc-options have been taken from here:
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass # Added.
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
# - -Wmissing-import-lists

library:
  source-dirs: src

tests:
  socket-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - socket-server
