name:                bridge
version:             0.1.0.0
license:             MIT
author:              "Vest"
maintainer:          "example@example.com"
copyright:           "2018 Vest"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            High-level library for streaming and RPCs over AMQP.
category:            Network

description:         See README.md

dependencies:
- amqp              >= 0.18 && < 1
- async             >= 2.2  && < 3
- base              >= 4.10 && < 5
- containers        >= 0.5  && < 1
- hashtables        >= 1.2  && < 2
- hostname          >= 1.0  && < 2
- stm               >= 2.4  && < 3
- streamly          >= 0.5  && < 1
- template-haskell  >= 2.10 && < 3
- text              >= 1.2  && < 2
- time              >= 1.8  && < 2
- utf8-string       >= 1.0  && < 2
- uuid              >= 1.3  && < 2
- vector            >= 0.12 && < 1
- vest-prelude


# The default-extensions and ghc-options have been taken from here:
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wmissing-import-lists

library:
  source-dirs: src

tests:
  bridge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bridge
