eztzExe: ~/.vest-hs/eztz-simple
tezosNodeUri: https://rpc.tezrpc.me
# This is the secret for bootstrap1 using liqdev sandbox.
addressSecret: edsk3gUfUPyBSfrS9CCgmCiQsTCHGkviBDusMxDJstFtojtc1zcpsh
timeoutSeconds: 5
