name:                bridge-client
version:             0.1.0.0
author:              "Vest"
copyright:           "2018 Vest"

extra-source-files:
- README.md

synopsis:            TypeScript types for interfacing with our Haskell-based backend.
category:            Network
description:         See README.md.

dependencies:
- aeson             >= 1.4  && < 2
- aeson-typescript  >= 0.1  && < 1
- base              >= 4.10 && < 5
- bridge
- directory         >= 1.3  && < 2
- ede               >= 0.2  && < 1
- filepath          >= 1.4  && < 2
- random            >= 1.1  && < 2
- services
- text              >= 1.2  && < 2
- text-replace      >= 0.0  && < 1
- template-haskell  >= 2.13 && < 3
- utf8-string       >= 1.0  && < 2
- vest-prelude

# The default-extensions and ghc-options have been taken from here:
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
# - GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UndecidableInstances # Added. In theory could make compiler never terminate.

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
# - -Wmissing-import-lists

library:
  source-dirs: src

executables:
  ts-callers:
    main:           Callers.hs
    other-modules:  []
    source-dirs:    bin
    dependencies:
    - bridge-client
  ts-types:
    main:           Types.hs
    other-modules:  []
    source-dirs:    bin
    dependencies:
    - bridge-client
